[package]
name = "tree-shake"
version = "0.1.0"
edition = "2021"

[lib]

[dependencies]
dashmap = "6.0.1"
oxc = { version = "0.24.3", features = ["codegen", "semantic", "minifier"] }
rustc-hash = "2.0.0"
