name: Publish Any Commit
on:
  pull_request:
  push:
    branches:
      - "**"
    tags:
      - "!**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
      
      - name: Use Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: 22
      
      - name: Setup PNPM
        uses: pnpm/action-setup@v4
        with:
          version: 9
      
      - name: Build NAPI
        run: |
          pnpm i
          pnpm build
        working-directory: ./napi

      - run: pnpx pkg-pr-new publish
